### ISSUE TITLE
Práctica EDT

### ISSUE THREAD

**Issue by IsraelNicolas61** [SistemasTecTlaxiaco/actividad-7-estructura-de-desglose-de-trabajo-edt-balam#1]
[Practica EDT.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-estructura-de-desglose-de-trabajo-edt-balam/files/9833519/Practica.EDT.pdf)

**Comment by carlos-chrs** [comment]
Muy bien Hecho.
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
